version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - db
    command: node build/app/index.js

  db:
    image: mysql:8.0.34
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=7827
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
